<?php

namespace App\Exports;

use PhpOffice\PhpWord\Element\Section;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\SimpleType\Jc;

/**
 * Builds the printable Inventory Monitoring Report as a Word (.docx)
 * document, styled to match InventoryReportExport (the Excel version):
 *
 *   - Same banner: "JC66 COFFEE SHOP" / "INVENTORY MONITORING REPORT" /
 *     Period / Generated By & Date
 *   - Brown (#6F4E37) table header row, white bold text, PHP peso
 *     currency formatting, and status row color-coding
 *   - Real Word page header (repeats on every page) and footer with
 *     "Generated by JC66 Coffee Shop POS", page numbers, and the
 *     generated date/time - matching the Excel print footer
 *
 * IMPORTANT: PhpWord does NOT auto-escape text passed into addText().
 * Every literal or user-supplied string (headings, meta, column labels)
 * MUST be run through esc() before being handed to PhpWord, or a stray
 * "&", "<", or ">" will produce invalid XML inside the .docx and Word
 * will refuse to open it / show a repair prompt. Table cell VALUES were
 * already escaped correctly; this fix extends that to headings/banner text.
 *
 * Usage - full 5-section report:
 *   $export = new InventoryReportWordExport($meta, $data);
 *   $path = $export->save();
 *
 * Usage - single section only (mirrors exportInventorySheet()):
 *   $path = $export->saveSection('summary'); // summary|stock-in|movement|batch-expiry|low-stock
 *
 * @param  array{period:string,generated_by:string,generated_date:string}  $meta
 * @param  array{summary:array,stockIn:array,movement:array,batches:array,lowStock:array}  $data
 */
class InventoryReportWordExport
{
    private const BROWN = '6F4E37';

    private const RED = 'F8CBCB';

    private const AMBER = 'FDE8B6';

    private const BORDER = ['borderSize' => 4, 'borderColor' => '999999'];

    public function __construct(private array $meta, private array $data)
    {
    }

    /**
     * Renders all 5 sections into one document and saves it to a temp file,
     * returning the path.
     */
    public function save(): string
    {
        return $this->render(array_keys($this->sectionConfig()));
    }

    /**
     * Renders a single named section (same keys as exportInventorySheet's
     * $sheet param: summary, stock-in, movement, batch-expiry, low-stock)
     * as its own standalone document, returning the temp file path.
     */
    public function saveSection(string $key): string
    {
        if (! isset($this->sectionConfig()[$key])) {
            throw new \InvalidArgumentException("Unknown report section [{$key}].");
        }

        return $this->render([$key]);
    }

    /**
     * Escapes a string for safe use inside PhpWord addText() calls.
     * PhpWord writes text as raw XML content — it does not escape for you.
     */
    private function esc(mixed $value): string
    {
        return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
    }

    /**
     * @param  array<int,string>  $sectionKeys
     */
    private function render(array $sectionKeys): string
    {
        $phpWord = new PhpWord();
        $phpWord->setDefaultFontName('Calibri');
        $phpWord->setDefaultFontSize(10);

        $section = $phpWord->addSection([
            'orientation' => 'landscape',
            'marginTop' => 700,
            'marginBottom' => 700,
            'marginLeft' => 600,
            'marginRight' => 600,
            'headerHeight' => 500,
            'footerHeight' => 500,
        ]);

        $this->addPageHeader($section);
        $this->addPageFooter($section);
        $this->addBanner($section);

        $config = $this->sectionConfig();
        foreach ($sectionKeys as $key) {
            $c = $config[$key];
            $this->addReportSection(
                $section,
                $c['heading'],
                $c['headings'],
                $c['rows'],
                $c['currencyCols'],
                $c['statusCol'],
                $c['footerRows'],
            );
        }

        $path = tempnam(sys_get_temp_dir(), 'jc66-inv-').'.docx';
        IOFactory::createWriter($phpWord, 'Word2007')->save($path);

        return $path;
    }

    /**
     * All 5 sections' config in one place, keyed the same as
     * IngredientController::exportInventorySheet()'s $sheet param, so
     * routes/URLs line up 1:1 with the Excel export. Column counts and
     * currency columns match buildInventoryReportData() exactly.
     */
    private function sectionConfig(): array
    {
        $summaryRows = $this->data['summary'] ?? [];

        return [
            'summary' => [
                'heading' => 'Inventory Summary',
                'headings' => ['Ingredient', 'Current Stock', 'Unit', 'Unit Cost (₱)', 'Total Value (₱)', 'Minimum Stock', 'Status'],
                'rows' => $summaryRows,
                'currencyCols' => [4, 5],
                'statusCol' => 7,
                'footerRows' => $this->summaryFooterRows($summaryRows),
            ],
            'stock-in' => [
                'heading' => 'Stock In / Restocking',
                'headings' => ['Date', 'Ingredient', 'Batch #', 'Quantity', 'Unit', 'Received Date', 'Expiry Date', 'Old Stock Cost (₱)', 'New Stock Cost (₱)', 'Note'],
                'rows' => $this->data['stockIn'] ?? [],
                'currencyCols' => [8, 9],
                'statusCol' => null,
                'footerRows' => [],
            ],
            'movement' => [
                'heading' => 'Inventory Movement',
                'headings' => ['Date', 'Ingredient / Product', 'Type', 'Quantity Change', 'Unit', 'Note'],
                'rows' => $this->data['movement'] ?? [],
                'currencyCols' => [],
                'statusCol' => null,
                'footerRows' => [],
            ],
            'batch-expiry' => [
                'heading' => 'Batch & Expiry',
                'headings' => ['Ingredient', 'Batch #', 'Received Date', 'Expiry Date', 'Remaining Quantity', 'Unit', 'Status'],
                'rows' => $this->data['batches'] ?? [],
                'currencyCols' => [],
                'statusCol' => 7,
                'footerRows' => [],
            ],
            'low-stock' => [
                'heading' => 'Low Stock Report',
                'headings' => ['Ingredient', 'Current Stock', 'Unit', 'Minimum Stock', 'Shortfall', 'Shortfall', 'Status'],
                'rows' => $this->data['lowStock'] ?? [],
                'currencyCols' => [],
                'statusCol' => 7,
                'footerRows' => [],
            ],
        ];
    }

    /**
     * Real Word header, repeats on every printed page - small, unobtrusive,
     * distinct from the big in-body banner.
     */
    private function addPageHeader(Section $section): void
    {
        $header = $section->addHeader();
        $header->addText(
            $this->esc('JC66 Coffee Shop — Inventory Monitoring Report'),
            ['bold' => true, 'size' => 9, 'color' => self::BROWN],
            ['alignment' => Jc::CENTER]
        );
    }

    private function addPageFooter(Section $section): void
    {
        $footer = $section->addFooter();
        $table = $footer->addTable(['width' => 100 * 50, 'unit' => 'pct']);
        $table->addRow();

        $left = $table->addCell(3000);
        $left->addText($this->esc('Generated by JC66 Coffee Shop POS'), ['size' => 8]);

        $center = $table->addCell(3000);
        // {PAGE}/{NUMPAGES} are PhpWord field placeholders, not literal
        // text — addPreserveText is the correct call here and does not
        // need escaping the same way, but the surrounding literal is safe
        // ASCII anyway.
        $center->addPreserveText('Page {PAGE} of {NUMPAGES}', ['size' => 8], ['alignment' => Jc::CENTER]);

        $right = $table->addCell(3000);
        $right->addText(
            $this->esc($this->meta['generated_date'] ?? now()->format('Y-m-d H:i')),
            ['size' => 8],
            ['alignment' => Jc::END]
        );
    }

    /**
     * The big banner block, matching rows 1-4 of every Excel sheet.
     * Period / Generated By / Generated Date come from request-supplied
     * meta (including a real user's name), so these MUST be escaped —
     * this is exactly what broke the last export ("Batch & Expiry" and
     * any "&" in a user's name would corrupt the XML otherwise).
     */
    private function addBanner(Section $section): void
    {
        $section->addText($this->esc('JC66 COFFEE SHOP'), ['bold' => true, 'size' => 18], ['alignment' => Jc::CENTER]);
        $section->addText($this->esc('INVENTORY MONITORING REPORT'), ['bold' => true, 'size' => 14], ['alignment' => Jc::CENTER, 'spaceAfter' => 120]);

        $section->addText(
            $this->esc('Period: '.($this->meta['period'] ?? '—')),
            ['italic' => true, 'size' => 10],
            ['alignment' => Jc::CENTER]
        );
        $section->addText(
            $this->esc('Generated By: '.($this->meta['generated_by'] ?? '—').'   |   Generated Date: '.($this->meta['generated_date'] ?? '—')),
            ['italic' => true, 'size' => 9],
            ['alignment' => Jc::CENTER, 'spaceAfter' => 300]
        );
    }

    /**
     * One report section: heading, table with brown header row, currency
     * formatting, status color-coding, and optional bold total row(s).
     *
     * @param  array<int,string>  $headings
     * @param  array<int,array<int,mixed>>  $rows
     * @param  array<int,int>  $currencyCols  1-indexed
     * @param  array<int,array<int,mixed>>  $footerRows
     */
    private function addReportSection(Section $section, string $heading, array $headings, array $rows, array $currencyCols, ?int $statusCol, array $footerRows): void
    {
        $section->addText(
            $this->esc($heading),
            ['bold' => true, 'size' => 12, 'color' => self::BROWN],
            ['spaceBefore' => 200, 'spaceAfter' => 80]
        );

        if ($rows === []) {
            $section->addText($this->esc('No records found for this period.'), ['italic' => true, 'size' => 9]);

            return;
        }

        $colCount = count($headings);
        $table = $section->addTable(array_merge(self::BORDER, ['width' => 100 * 50, 'unit' => 'pct']));

        // Header row
        $table->addRow(null, ['tblHeader' => true]);
        foreach ($headings as $h) {
            $cell = $table->addCell(9000 / max($colCount, 1), ['bgColor' => self::BROWN]);
            $cell->addText($this->esc($h), ['bold' => true, 'color' => 'FFFFFF', 'size' => 9], ['alignment' => Jc::CENTER]);
        }

        // Data rows
        foreach ($rows as $row) {
            $bg = $this->rowColorFor($row, $statusCol);
            $table->addRow();
            foreach ($row as $i => $value) {
                $colIndex = $i + 1;
                $isCurrency = in_array($colIndex, $currencyCols, true) && is_numeric($value);
                $display = $isCurrency
                    ? '₱'.number_format((float) $value, 2)
                    : (string) $value;

                $cellStyle = $bg ? ['bgColor' => $bg] : [];
                $cell = $table->addCell(9000 / max($colCount, 1), $cellStyle);
                $cell->addText(
                    $this->esc($display),
                    ['size' => 9],
                    ['alignment' => $isCurrency ? Jc::END : Jc::START]
                );
            }
        }

        // Footer / total rows
        foreach ($footerRows as $footerRow) {
            $table->addRow();
            foreach ($footerRow as $i => $value) {
                $colIndex = $i + 1;
                $isCurrency = in_array($colIndex, $currencyCols, true) && is_numeric($value);
                $display = $isCurrency
                    ? '₱'.number_format((float) $value, 2)
                    : (string) $value;

                $cell = $table->addCell(9000 / max($colCount, 1));
                $cell->addText(
                    $this->esc($display),
                    ['bold' => true, 'size' => 9],
                    ['alignment' => $isCurrency ? Jc::END : Jc::START]
                );
            }
        }
    }

    /**
     * @param  array<int,mixed>  $row
     */
    private function rowColorFor(array $row, ?int $statusCol): ?string
    {
        if (! $statusCol) {
            return null;
        }

        $value = strtolower((string) ($row[$statusCol - 1] ?? ''));

        return match (true) {
            str_contains($value, 'out of stock'), str_contains($value, 'expired') => self::RED,
            str_contains($value, 'low'), str_contains($value, 'expiring') => self::AMBER,
            default => null,
        };
    }

    /**
     * TOTAL INVENTORY VALUE row, matching InventorySummarySheet::footerRows().
     */
    private function summaryFooterRows(array $rows): array
    {
        if ($rows === []) {
            return [];
        }

        $total = array_sum(array_map(fn (array $r) => (float) ($r[4] ?? 0), $rows));

        return [
            ['', '', '', 'TOTAL INVENTORY VALUE', $total, '', ''],
        ];
    }
}