<?php

namespace App\Exports;

use PhpOffice\PhpWord\Element\Section;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\SimpleType\Jc;

/**
 * Builds the printable Sales Report as a Word (.docx) document — a single
 * Transaction Log section with a Total Sales row at the bottom — styled to
 * match InventoryReportWordExport / SalesReportExport (the Excel version).
 *
 * Includes completed, refunded, and voided transactions (spec section 13);
 * refunded/voided rows are shaded (amber/red) and excluded from TOTAL SALES.
 *
 * IMPORTANT: same escaping requirement as InventoryReportWordExport — every
 * literal or user-supplied string MUST go through esc() before addText().
 *
 * Usage:
 *   $path = (new SalesReportWordExport($meta, $data))->save();
 *
 * @param  array{period:string,generated_by:string,generated_date:string}  $meta
 * @param  array{transactionLog: array<int,array>}  $data
 */
class SalesReportWordExport
{
    private const BROWN = '6F4E37';

    private const AMBER = 'FDE8B6';

    private const RED = 'F8CBCB';

    private const BORDER = ['borderSize' => 4, 'borderColor' => '999999'];

    private const SECTIONS = ['transaction-log'];

    public function __construct(private array $meta, private array $data)
    {
    }

    public function save(): string
    {
        return $this->render(self::SECTIONS);
    }

    public function saveSection(string $key): string
    {
        if (! in_array($key, self::SECTIONS, true)) {
            throw new \InvalidArgumentException("Unknown report section [{$key}].");
        }

        return $this->render([$key]);
    }

    private function esc(mixed $value): string
    {
        return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
    }

    /**
     * @param  array<int,string>  $sectionKeys
     */
    private function render(array $sectionKeys): string
    {
        $phpWord = new PhpWord();
        $phpWord->setDefaultFontName('Calibri');
        $phpWord->setDefaultFontSize(10);

        $section = $phpWord->addSection([
            'orientation' => 'landscape',
            'marginTop' => 700,
            'marginBottom' => 700,
            'marginLeft' => 600,
            'marginRight' => 600,
            'headerHeight' => 500,
            'footerHeight' => 500,
        ]);

        $this->addPageHeader($section);
        $this->addPageFooter($section);
        $this->addBanner($section);

        foreach ($sectionKeys as $key) {
            match ($key) {
                'transaction-log' => $this->addTransactionLogSection($section),
                default => null,
            };
        }

        $path = tempnam(sys_get_temp_dir(), 'jc66-sales-').'.docx';
        IOFactory::createWriter($phpWord, 'Word2007')->save($path);

        return $path;
    }

    private function addPageHeader(Section $section): void
    {
        $header = $section->addHeader();
        $header->addText(
            $this->esc('JC66 Coffee Shop — Sales Report'),
            ['bold' => true, 'size' => 9, 'color' => self::BROWN],
            ['alignment' => Jc::CENTER]
        );
    }

    private function addPageFooter(Section $section): void
    {
        $footer = $section->addFooter();
        $table = $footer->addTable(['width' => 100 * 50, 'unit' => 'pct']);
        $table->addRow();

        $left = $table->addCell(3000);
        $left->addText($this->esc('Generated by JC66 Coffee Shop POS'), ['size' => 8]);

        $center = $table->addCell(3000);
        $center->addPreserveText('Page {PAGE} of {NUMPAGES}', ['size' => 8], ['alignment' => Jc::CENTER]);

        $right = $table->addCell(3000);
        $right->addText(
            $this->esc($this->meta['generated_date'] ?? now()->format('Y-m-d H:i')),
            ['size' => 8],
            ['alignment' => Jc::END]
        );
    }

    private function addBanner(Section $section): void
    {
        $section->addText($this->esc('JC66 COFFEE SHOP'), ['bold' => true, 'size' => 18], ['alignment' => Jc::CENTER]);
        $section->addText($this->esc('SALES REPORT'), ['bold' => true, 'size' => 14], ['alignment' => Jc::CENTER, 'spaceAfter' => 120]);

        $section->addText(
            $this->esc('Period: '.($this->meta['period'] ?? '—')),
            ['italic' => true, 'size' => 10],
            ['alignment' => Jc::CENTER]
        );
        $section->addText(
            $this->esc('Generated By: '.($this->meta['generated_by'] ?? '—').'   |   Generated Date: '.($this->meta['generated_date'] ?? '—')),
            ['italic' => true, 'size' => 9],
            ['alignment' => Jc::CENTER, 'spaceAfter' => 300]
        );
    }

    private function peso(mixed $value): string
    {
        return '₱'.number_format((float) $value, 2);
    }

    /**
     * Transaction Log — the only section in this simplified Sales Report
     * export. Refunded/voided rows are shaded and excluded from the
     * TOTAL SALES row appended at the bottom.
     */
    private function addTransactionLogSection(Section $section): void
    {
        $headings = ['Transaction #', 'Date', 'Time', 'Cashier', 'Order #', 'Order Type', 'Payment Method', 'GCash Ref #', 'Amount Received (₱)', 'Change (₱)', 'Total (₱)', 'Status', 'Notes', 'Created At'];
        $rows = $this->data['transactionLog'] ?? [];
        $currencyCols = [9, 10, 11];

        $section->addText($this->esc('Transaction Log'), ['bold' => true, 'size' => 12, 'color' => self::BROWN], ['spaceBefore' => 200, 'spaceAfter' => 80]);

        if ($rows === []) {
            $section->addText($this->esc('No records found for this period.'), ['italic' => true, 'size' => 9]);

            return;
        }

        $colCount = count($headings);
        $table = $section->addTable(array_merge(self::BORDER, ['width' => 100 * 50, 'unit' => 'pct']));

        // Header row
        $table->addRow(null, ['tblHeader' => true]);
        foreach ($headings as $h) {
            $cell = $table->addCell(9000 / max($colCount, 1), ['bgColor' => self::BROWN]);
            $cell->addText($this->esc($h), ['bold' => true, 'color' => 'FFFFFF', 'size' => 9], ['alignment' => Jc::CENTER]);
        }

        $totalSales = 0.0;

        // Data rows — status is array index 11 (col 12)
        foreach ($rows as $row) {
            $status = (string) ($row[11] ?? '');
            if ($status === 'Completed') {
                $totalSales += (float) ($row[10] ?? 0);
            }

            $bg = match ($status) {
                'Refunded' => self::AMBER,
                'Voided' => self::RED,
                default => null,
            };

            $table->addRow();
            foreach ($row as $i => $value) {
                $colIndex = $i + 1;
                $isCurrency = in_array($colIndex, $currencyCols, true) && is_numeric($value);
                $display = $isCurrency ? $this->peso($value) : (string) $value;

                $cellStyle = $bg ? ['bgColor' => $bg] : [];
                $cell = $table->addCell(9000 / max($colCount, 1), $cellStyle);
                $cell->addText(
                    $this->esc($display),
                    ['size' => 9],
                    ['alignment' => $isCurrency ? Jc::END : Jc::START]
                );
            }
        }

        // TOTAL SALES row — completed transactions only
        $table->addRow();
        foreach (range(1, $colCount) as $colIndex) {
            $cell = $table->addCell(9000 / max($colCount, 1));

            if ($colIndex === 10) {
                $cell->addText($this->esc('TOTAL SALES'), ['bold' => true, 'size' => 9], ['alignment' => Jc::END]);
            } elseif ($colIndex === 11) {
                $cell->addText($this->esc($this->peso($totalSales)), ['bold' => true, 'size' => 9], ['alignment' => Jc::END]);
            } else {
                $cell->addText('', ['size' => 9]);
            }
        }
    }
}