<?php

namespace App\Exports;

use PhpOffice\PhpWord\Element\Section;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\SimpleType\Jc;

/**
 * Builds the printable Sales Report as a Word (.docx) document, styled to
 * match InventoryReportWordExport / SalesReportExport (the Excel version):
 *
 *   - Same banner: "JC66 COFFEE SHOP" / "SALES REPORT" / Period /
 *     Generated By & Date
 *   - Brown (#6F4E37) table header rows, white bold text, peso currency
 *     and percentage formatting
 *   - Real Word page header/footer, same shape as the inventory export
 *
 * IMPORTANT: same escaping requirement as InventoryReportWordExport — every
 * literal or user-supplied string MUST go through esc() before addText().
 *
 * Usage — full report:
 *   $path = (new SalesReportWordExport($meta, $data))->save();
 *
 * Usage — single section (mirrors exportSalesSheet()):
 *   $path = (new SalesReportWordExport($meta, $data))->saveSection('summary');
 *   // summary|transaction-log|product-sales|payment-summary|sales-by-period
 *
 * @param  array{period:string,generated_by:string,generated_date:string}  $meta
 * @param  array{
 *     summary: array,
 *     paymentSummary: array<int,array>,
 *     paymentSummaryRows: array<int,array>,
 *     orderTypeSummary: array<int,array>,
 *     bestSellers: array<int,array>,
 *     transactionLog: array<int,array>,
 *     productSales: array<int,array>,
 *     salesByPeriodRows: array<int,array>,
 * }  $data
 */
class SalesReportWordExport
{
    private const BROWN = '6F4E37';

    private const BORDER = ['borderSize' => 4, 'borderColor' => '999999'];

    private const SECTIONS = ['summary', 'transaction-log', 'product-sales', 'payment-summary', 'sales-by-period'];

    public function __construct(private array $meta, private array $data)
    {
    }

    public function save(): string
    {
        return $this->render(self::SECTIONS);
    }

    public function saveSection(string $key): string
    {
        if (! in_array($key, self::SECTIONS, true)) {
            throw new \InvalidArgumentException("Unknown report section [{$key}].");
        }

        return $this->render([$key]);
    }

    private function esc(mixed $value): string
    {
        return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
    }

    /**
     * @param  array<int,string>  $sectionKeys
     */
    private function render(array $sectionKeys): string
    {
        $phpWord = new PhpWord();
        $phpWord->setDefaultFontName('Calibri');
        $phpWord->setDefaultFontSize(10);

        $section = $phpWord->addSection([
            'orientation' => 'landscape',
            'marginTop' => 700,
            'marginBottom' => 700,
            'marginLeft' => 600,
            'marginRight' => 600,
            'headerHeight' => 500,
            'footerHeight' => 500,
        ]);

        $this->addPageHeader($section);
        $this->addPageFooter($section);
        $this->addBanner($section);

        foreach ($sectionKeys as $key) {
            match ($key) {
                'summary' => $this->addSummarySection($section),
                'transaction-log' => $this->addReportSection(
                    $section,
                    '2. Transaction Log',
                    ['Transaction #', 'Date', 'Time', 'Cashier', 'Order #', 'Order Type', 'Payment Method', 'GCash Ref #', 'Amount Received (₱)', 'Change (₱)', 'Total (₱)', 'Status', 'Created At'],
                    $this->data['transactionLog'] ?? [],
                    [9, 10, 11],
                    [],
                ),
                'product-sales' => $this->addReportSection(
                    $section,
                    '3. Product Sales Breakdown',
                    ['Product', 'Category', 'Qty Sold', 'Unit Price (₱)', 'Revenue (₱)', 'COGS (₱)', 'Gross Profit (₱)', 'Margin (%)'],
                    $this->data['productSales'] ?? [],
                    [4, 5, 6, 7],
                    [8],
                ),
                'payment-summary' => $this->addReportSection(
                    $section,
                    '4. Payment Method Summary',
                    ['Payment Method', 'Transactions', 'Total Sales (₱)', 'Percentage (%)'],
                    $this->data['paymentSummaryRows'] ?? [],
                    [3],
                    [4],
                ),
                'sales-by-period' => $this->addReportSection(
                    $section,
                    '5. Sales by Period',
                    ['Period', 'Transactions', 'Items Sold', 'Sales (₱)', 'COGS (₱)', 'Gross Profit (₱)', 'Margin (%)'],
                    $this->data['salesByPeriodRows'] ?? [],
                    [4, 5, 6],
                    [7],
                ),
                default => null,
            };
        }

        $path = tempnam(sys_get_temp_dir(), 'jc66-sales-').'.docx';
        IOFactory::createWriter($phpWord, 'Word2007')->save($path);

        return $path;
    }

    private function addPageHeader(Section $section): void
    {
        $header = $section->addHeader();
        $header->addText(
            $this->esc('JC66 Coffee Shop — Sales Report'),
            ['bold' => true, 'size' => 9, 'color' => self::BROWN],
            ['alignment' => Jc::CENTER]
        );
    }

    private function addPageFooter(Section $section): void
    {
        $footer = $section->addFooter();
        $table = $footer->addTable(['width' => 100 * 50, 'unit' => 'pct']);
        $table->addRow();

        $left = $table->addCell(3000);
        $left->addText($this->esc('Generated by JC66 Coffee Shop POS'), ['size' => 8]);

        $center = $table->addCell(3000);
        $center->addPreserveText('Page {PAGE} of {NUMPAGES}', ['size' => 8], ['alignment' => Jc::CENTER]);

        $right = $table->addCell(3000);
        $right->addText(
            $this->esc($this->meta['generated_date'] ?? now()->format('Y-m-d H:i')),
            ['size' => 8],
            ['alignment' => Jc::END]
        );
    }

    private function addBanner(Section $section): void
    {
        $section->addText($this->esc('JC66 COFFEE SHOP'), ['bold' => true, 'size' => 18], ['alignment' => Jc::CENTER]);
        $section->addText($this->esc('SALES REPORT'), ['bold' => true, 'size' => 14], ['alignment' => Jc::CENTER, 'spaceAfter' => 120]);

        $section->addText(
            $this->esc('Period: '.($this->meta['period'] ?? '—')),
            ['italic' => true, 'size' => 10],
            ['alignment' => Jc::CENTER]
        );
        $section->addText(
            $this->esc('Generated By: '.($this->meta['generated_by'] ?? '—').'   |   Generated Date: '.($this->meta['generated_date'] ?? '—')),
            ['italic' => true, 'size' => 9],
            ['alignment' => Jc::CENTER, 'spaceAfter' => 300]
        );
    }

    /**
     * "1. Sales Summary" — KPIs, then Payment Summary, Order Type Summary,
     * and Best Selling Products, block-for-block matching
     * App\Exports\Sheets\SalesSummarySheet.
     */
    private function addSummarySection(Section $section): void
    {
        $summary = $this->data['summary'] ?? [];

        $section->addText($this->esc('1. Sales Summary'), ['bold' => true, 'size' => 12, 'color' => self::BROWN], ['spaceBefore' => 200, 'spaceAfter' => 80]);

        $this->addSimpleTable($section, ['Metric', 'Value'], [
            ['Total Sales', $this->peso($summary['total_sales'] ?? 0)],
            ['Total Transactions', (string) ($summary['transaction_count'] ?? 0)],
            ['Items Sold', (string) ($summary['items_sold'] ?? 0)],
            ['Average Sale', $this->peso($summary['average_sale'] ?? 0)],
            ['Total COGS', $this->peso($summary['total_cogs'] ?? 0)],
            ['Gross Profit', $this->peso($summary['gross_profit'] ?? 0)],
            ['Gross Margin', $this->percent($summary['gross_margin'] ?? 0)],
        ]);

        $section->addText($this->esc('2. Payment Summary'), ['bold' => true, 'size' => 12, 'color' => self::BROWN], ['spaceBefore' => 200, 'spaceAfter' => 80]);
        $paymentRows = collect($this->data['paymentSummary'] ?? [])->map(fn ($p) => [
            $p['label'], (string) $p['transactions'], $this->peso($p['total_sales']), $this->percent($p['percentage']),
        ])->all();
        $this->addSimpleTable($section, ['Payment Method', 'Transactions', 'Total Sales', 'Percentage'], $paymentRows);

        $section->addText($this->esc('3. Order Type Summary'), ['bold' => true, 'size' => 12, 'color' => self::BROWN], ['spaceBefore' => 200, 'spaceAfter' => 80]);
        $orderRows = collect($this->data['orderTypeSummary'] ?? [])->map(fn ($o) => [
            $o['label'], (string) $o['transactions'], (string) $o['items_sold'], $this->peso($o['total_sales']),
        ])->all();
        $this->addSimpleTable($section, ['Order Type', 'Transactions', 'Items Sold', 'Total Sales'], $orderRows);

        $section->addText($this->esc('4. Best Selling Products'), ['bold' => true, 'size' => 12, 'color' => self::BROWN], ['spaceBefore' => 200, 'spaceAfter' => 80]);
        $bestSellerRows = collect($this->data['bestSellers'] ?? [])->map(fn ($b) => [
            $b['name'], (string) $b['quantity'], $this->peso($b['total']),
        ])->all();
        $this->addSimpleTable($section, ['Product', 'Quantity Sold', 'Revenue'], $bestSellerRows);
    }

    private function peso(mixed $value): string
    {
        return '₱'.number_format((float) $value, 2);
    }

    private function percent(mixed $value): string
    {
        return number_format((float) $value, 2).'%';
    }

    /**
     * Small header+rows table used only by addSummarySection(); values
     * are pre-formatted strings.
     *
     * @param  array<int,string>  $headings
     * @param  array<int,array<int,string>>  $rows
     */
    private function addSimpleTable(Section $section, array $headings, array $rows): void
    {
        if ($rows === []) {
            $section->addText($this->esc('No records found for this period.'), ['italic' => true, 'size' => 9]);

            return;
        }

        $colCount = count($headings);
        $table = $section->addTable(array_merge(self::BORDER, ['width' => 60 * 50, 'unit' => 'pct']));

        $table->addRow(null, ['tblHeader' => true]);
        foreach ($headings as $h) {
            $cell = $table->addCell(9000 / max($colCount, 1), ['bgColor' => self::BROWN]);
            $cell->addText($this->esc($h), ['bold' => true, 'color' => 'FFFFFF', 'size' => 9], ['alignment' => Jc::CENTER]);
        }

        foreach ($rows as $row) {
            $table->addRow();
            foreach ($row as $i => $value) {
                $cell = $table->addCell(9000 / max($colCount, 1));
                $cell->addText($this->esc($value), ['size' => 9], ['alignment' => $i === 0 ? Jc::START : Jc::END]);
            }
        }
    }

    /**
     * Generic table section for Transaction Log / Product Sales /
     * Payment Summary / Sales by Period — same shape as
     * InventoryReportWordExport::addReportSection().
     *
     * @param  array<int,string>  $headings
     * @param  array<int,array<int,mixed>>  $rows
     * @param  array<int,int>  $currencyCols  1-indexed
     * @param  array<int,int>  $percentCols  1-indexed
     */
    private function addReportSection(Section $section, string $heading, array $headings, array $rows, array $currencyCols, array $percentCols): void
    {
        $section->addText($this->esc($heading), ['bold' => true, 'size' => 12, 'color' => self::BROWN], ['spaceBefore' => 200, 'spaceAfter' => 80]);

        if ($rows === []) {
            $section->addText($this->esc('No records found for this period.'), ['italic' => true, 'size' => 9]);

            return;
        }

        $colCount = count($headings);
        $table = $section->addTable(array_merge(self::BORDER, ['width' => 100 * 50, 'unit' => 'pct']));

        $table->addRow(null, ['tblHeader' => true]);
        foreach ($headings as $h) {
            $cell = $table->addCell(9000 / max($colCount, 1), ['bgColor' => self::BROWN]);
            $cell->addText($this->esc($h), ['bold' => true, 'color' => 'FFFFFF', 'size' => 9], ['alignment' => Jc::CENTER]);
        }

        foreach ($rows as $row) {
            $table->addRow();
            foreach ($row as $i => $value) {
                $colIndex = $i + 1;
                $isCurrency = in_array($colIndex, $currencyCols, true) && is_numeric($value);
                $isPercent = in_array($colIndex, $percentCols, true) && is_numeric($value);
                $display = match (true) {
                    $isCurrency => $this->peso($value),
                    $isPercent => $this->percent($value),
                    default => (string) $value,
                };

                $cell = $table->addCell(9000 / max($colCount, 1));
                $cell->addText(
                    $this->esc($display),
                    ['size' => 9],
                    ['alignment' => ($isCurrency || $isPercent) ? Jc::END : Jc::START]
                );
            }
        }
    }
}