<?php

namespace App\Exports\Sheets;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;

/**
 * Shared professional layout for JC66 Coffee Shop
 * Inventory Monitoring Excel reports.
 *
 * Layout:
 *
 * Row 1  JC66 COFFEE SHOP
 * Row 2  INVENTORY MONITORING REPORT
 * Row 3  Period: ...
 * Row 4  Generated By: ... | Generated Date: ...
 * Row 5  Blank
 * Row 6  Report Section
 * Row 7  Table Headers
 * Row 8+ Data
 *       Optional Footer / Total Rows
 */
abstract class BaseReportSheet implements FromArray, ShouldAutoSize, WithEvents, WithTitle
{
    /**
     * @param array{
     *     period:string,
     *     generated_by:string,
     *     generated_date:string
     * } $meta
     *
     * @param array<int,array<int,mixed>> $rows
     */
    public function __construct(
        protected array $meta,
        protected array $rows
    ) {
    }

    /**
     * Excel tab name.
     *
     * Maximum 31 characters.
     */
    abstract public function title(): string;

    /**
     * Section heading printed above the table.
     */
    abstract public function reportHeading(): string;

    /**
     * Table column headings.
     */
    abstract public function headings(): array;

    /**
     * 1-indexed columns that use Philippine Peso format.
     */
    abstract public function currencyColumns(): array;

    /**
     * Optional status column.
     *
     * Examples:
     * Low Stock
     * Out of Stock
     * Expiring Soon
     * Expired
     */
    public function statusColumn(): ?int
    {
        return null;
    }

    /**
     * Optional total/footer rows.
     */
    public function footerRows(): array
    {
        return [];
    }

    /**
     * Build worksheet data.
     */
    public function array(): array
    {
        $rows = [
            ['JC66 COFFEE SHOP'],
            ['INVENTORY MONITORING REPORT'],
            ['Period: ' . ($this->meta['period'] ?? '—')],
            [
                'Generated By: ' .
                ($this->meta['generated_by'] ?? '—') .
                '   |   Generated Date: ' .
                ($this->meta['generated_date'] ?? '—'),
            ],
            [],
            [$this->reportHeading()],
            $this->headings(),
        ];

        if ($this->rows === []) {
            $rows[] = ['No records found for this period.'];
        } else {
            foreach ($this->rows as $row) {
                $rows[] = $row;
            }
        }

        foreach ($this->footerRows() as $footerRow) {
            $rows[] = $footerRow;
        }

        return $rows;
    }

    /**
     * Register Excel events.
     */
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $this->applyStyling($event);
            },
        ];
    }

    /**
     * Apply professional Excel styling.
     */
    protected function applyStyling(AfterSheet $event): void
    {
        $sheet = $event->sheet->getDelegate();

        $columnCount = max(count($this->headings()), 1);
        $lastColumn = Coordinate::stringFromColumnIndex($columnCount);

        $headerRow = 7;
        $firstDataRow = 8;

        /*
         * ---------------------------------------------------------
         * Calculate rows
         * ---------------------------------------------------------
         */

        $dataCount = max(count($this->rows), 1);

        $lastDataRow = $headerRow + $dataCount;

        $footerRows = $this->footerRows();
        $footerCount = count($footerRows);

        $footerStart = $lastDataRow + 1;
        $footerEnd = $footerStart + $footerCount - 1;

        $lastRow = $footerCount > 0
            ? $footerEnd
            : $lastDataRow;

        /*
         * ---------------------------------------------------------
         * Overall worksheet
         * ---------------------------------------------------------
         */

        $sheet->getDefaultRowDimension()->setRowHeight(20);

        /*
         * ---------------------------------------------------------
         * Header area
         * ---------------------------------------------------------
         */

        foreach ([1, 2, 3, 4, 6] as $row) {
            $sheet->mergeCells(
                "A{$row}:{$lastColumn}{$row}"
            );
        }

        /*
         * JC66 COFFEE SHOP
         */
        $sheet->getStyle("A1:{$lastColumn}1")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);

        $sheet->getStyle('A1')
            ->getFont()
            ->setBold(true)
            ->setSize(16);

        $sheet->getRowDimension(1)->setRowHeight(27);

        /*
         * Main report title
         */
        $sheet->getStyle("A2:{$lastColumn}2")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);

        $sheet->getStyle('A2')
            ->getFont()
            ->setBold(true)
            ->setSize(13);

        $sheet->getRowDimension(2)->setRowHeight(23);

        /*
         * Period
         */
        $sheet->getStyle("A3:{$lastColumn}3")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);

        $sheet->getStyle('A3')
            ->getFont()
            ->setSize(10)
            ->setItalic(true);

        /*
         * Generated information
         */
        $sheet->getStyle("A4:{$lastColumn}4")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);

        $sheet->getStyle('A4')
            ->getFont()
            ->setSize(9)
            ->setItalic(true);

        /*
         * ---------------------------------------------------------
         * Section heading
         * ---------------------------------------------------------
         */

        $sheet->getStyle("A6:{$lastColumn}6")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_LEFT)
            ->setVertical(Alignment::VERTICAL_CENTER);

        $sheet->getStyle("A6:{$lastColumn}6")
            ->getFont()
            ->setBold(true)
            ->setSize(11);

        $sheet->getStyle("A6:{$lastColumn}6")
            ->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()
            ->setRGB('EDE7E3');

        $sheet->getStyle("A6:{$lastColumn}6")
            ->getBorders()
            ->getBottom()
            ->setBorderStyle(Border::BORDER_MEDIUM);

        $sheet->getRowDimension(6)->setRowHeight(23);

        /*
         * ---------------------------------------------------------
         * Table header
         * ---------------------------------------------------------
         */

        $headerRange = "A{$headerRow}:{$lastColumn}{$headerRow}";

        $sheet->getStyle($headerRange)
            ->getFont()
            ->setBold(true)
            ->getColor()
            ->setRGB('FFFFFF');

        $sheet->getStyle($headerRange)
            ->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()
            ->setRGB('6F4E37');

        $sheet->getStyle($headerRange)
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER)
            ->setWrapText(true);

        $sheet->getStyle($headerRange)
            ->getBorders()
            ->getAllBorders()
            ->setBorderStyle(Border::BORDER_THIN);

        $sheet->getRowDimension($headerRow)->setRowHeight(30);

        /*
         * ---------------------------------------------------------
         * Data rows
         * ---------------------------------------------------------
         */

        if ($this->rows !== []) {
            $dataRange = "A{$firstDataRow}:{$lastColumn}{$lastDataRow}";

            $sheet->getStyle($dataRange)
                ->getAlignment()
                ->setVertical(Alignment::VERTICAL_CENTER);

            $sheet->getStyle($dataRange)
                ->getBorders()
                ->getAllBorders()
                ->setBorderStyle(Border::BORDER_THIN);

            /*
             * Alternating row appearance.
             */
            for (
                $rowNumber = $firstDataRow;
                $rowNumber <= $lastDataRow;
                $rowNumber++
            ) {
                if (($rowNumber - $firstDataRow) % 2 === 1) {
                    $sheet->getStyle(
                        "A{$rowNumber}:{$lastColumn}{$rowNumber}"
                    )
                        ->getFill()
                        ->setFillType(Fill::FILL_SOLID)
                        ->getStartColor()
                        ->setRGB('F8F5F3');
                }
            }
        }

        /*
         * ---------------------------------------------------------
         * No records message
         * ---------------------------------------------------------
         */

        if ($this->rows === []) {
            $sheet->mergeCells(
                "A{$firstDataRow}:{$lastColumn}{$firstDataRow}"
            );

            $sheet->getStyle(
                "A{$firstDataRow}:{$lastColumn}{$firstDataRow}"
            )
                ->getAlignment()
                ->setHorizontal(Alignment::HORIZONTAL_CENTER)
                ->setVertical(Alignment::VERTICAL_CENTER);

            $sheet->getStyle(
                "A{$firstDataRow}:{$lastColumn}{$firstDataRow}"
            )
                ->getFont()
                ->setItalic(true);

            $sheet->getStyle(
                "A{$firstDataRow}:{$lastColumn}{$firstDataRow}"
            )
                ->getBorders()
                ->getAllBorders()
                ->setBorderStyle(Border::BORDER_THIN);

            $sheet->getRowDimension($firstDataRow)->setRowHeight(28);
        }

        /*
         * ---------------------------------------------------------
         * Currency formatting
         * ---------------------------------------------------------
         */

        foreach ($this->currencyColumns() as $columnIndex) {
            if (
                $columnIndex < 1 ||
                $columnIndex > $columnCount
            ) {
                continue;
            }

            $columnLetter = Coordinate::stringFromColumnIndex(
                $columnIndex
            );

            $sheet->getStyle(
                "{$columnLetter}{$firstDataRow}:{$columnLetter}{$lastRow}"
            )
                ->getNumberFormat()
                ->setFormatCode('₱#,##0.00');

            $sheet->getStyle(
                "{$columnLetter}{$firstDataRow}:{$columnLetter}{$lastRow}"
            )
                ->getAlignment()
                ->setHorizontal(
                    Alignment::HORIZONTAL_RIGHT
                );
        }

        /*
         * ---------------------------------------------------------
         * Status color coding
         * ---------------------------------------------------------
         */

        if (
            $this->rows !== [] &&
            ($statusColumn = $this->statusColumn())
        ) {
            if (
                $statusColumn >= 1 &&
                $statusColumn <= $columnCount
            ) {
                $statusLetter = Coordinate::stringFromColumnIndex(
                    $statusColumn
                );

                foreach ($this->rows as $index => $row) {
                    $value = strtolower(
                        trim(
                            (string) (
                                $row[$statusColumn - 1] ?? ''
                            )
                        )
                    );

                    $rowNumber = $firstDataRow + $index;

                    $fillColor = match (true) {
                        str_contains($value, 'out of stock'),
                        str_contains($value, 'expired'),
                        str_contains($value, 'critical')
                            => 'F8CBCB',

                        str_contains($value, 'low'),
                        str_contains($value, 'expiring'),
                        str_contains($value, 'warning')
                            => 'FDE8B6',

                        str_contains($value, 'available'),
                        str_contains($value, 'good'),
                        str_contains($value, 'normal')
                            => 'D9EAD3',

                        default => null,
                    };

                    if ($fillColor !== null) {
                        $sheet->getStyle(
                            "{$statusLetter}{$rowNumber}"
                        )
                            ->getFill()
                            ->setFillType(
                                Fill::FILL_SOLID
                            )
                            ->getStartColor()
                            ->setRGB($fillColor);

                        $sheet->getStyle(
                            "{$statusLetter}{$rowNumber}"
                        )
                            ->getFont()
                            ->setBold(true);
                    }
                }
            }
        }

        /*
         * ---------------------------------------------------------
         * Footer / total rows
         * ---------------------------------------------------------
         */

        if ($footerCount > 0) {
            $footerRange =
                "A{$footerStart}:{$lastColumn}{$footerEnd}";

            $sheet->getStyle($footerRange)
                ->getFont()
                ->setBold(true);

            $sheet->getStyle($footerRange)
                ->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()
                ->setRGB('EDE7E3');

            $sheet->getStyle($footerRange)
                ->getBorders()
                ->getAllBorders()
                ->setBorderStyle(Border::BORDER_THIN);

            $sheet->getStyle($footerRange)
                ->getAlignment()
                ->setVertical(
                    Alignment::VERTICAL_CENTER
                );
        }

        /*
         * ---------------------------------------------------------
         * Column alignment
         * ---------------------------------------------------------
         */

        for (
            $columnIndex = 1;
            $columnIndex <= $columnCount;
            $columnIndex++
        ) {
            $columnLetter = Coordinate::stringFromColumnIndex(
                $columnIndex
            );

            $sheet->getStyle(
                "{$columnLetter}{$firstDataRow}:{$columnLetter}{$lastRow}"
            )
                ->getAlignment()
                ->setVertical(
                    Alignment::VERTICAL_CENTER
                );
        }

        /*
         * ---------------------------------------------------------
         * Freeze table header
         * ---------------------------------------------------------
         */

        $sheet->freezePane("A{$firstDataRow}");

        /*
         * ---------------------------------------------------------
         * Auto filter
         * ---------------------------------------------------------
         */

        if ($this->rows !== []) {
            $sheet->setAutoFilter($headerRange);
        }

        /*
         * ---------------------------------------------------------
         * Print setup
         * ---------------------------------------------------------
         */

        $pageSetup = $sheet->getPageSetup();

        $pageSetup
            ->setOrientation(
                PageSetup::ORIENTATION_LANDSCAPE
            )
            ->setPaperSize(
                PageSetup::PAPERSIZE_A4
            )
            ->setFitToWidth(1)
            ->setFitToHeight(0);

        /*
         * Repeat table header on every printed page.
         */
        $pageSetup->setRowsToRepeatAtTopByStartAndEnd(
            $headerRow,
            $headerRow
        );

        /*
         * Print area.
         */
        $pageSetup->setPrintArea(
            "A1:{$lastColumn}{$lastRow}"
        );

        /*
         * Center horizontally when printed.
         */
        $pageSetup->setHorizontalCentered(true);

        /*
         * ---------------------------------------------------------
         * Page margins
         * ---------------------------------------------------------
         */

        $sheet->getPageMargins()
            ->setTop(0.55)
            ->setBottom(0.55)
            ->setLeft(0.35)
            ->setRight(0.35)
            ->setHeader(0.20)
            ->setFooter(0.25);

        /*
         * ---------------------------------------------------------
         * Professional Excel header
         * ---------------------------------------------------------
         */

        $sheet->getHeaderFooter()->setOddHeader(
            '&L&8JC66 COFFEE SHOP' .
            '&R&8INVENTORY MONITORING REPORT'
        );

        /*
         * ---------------------------------------------------------
         * Professional Excel footer
         * ---------------------------------------------------------
         */

        $generatedDate = now()->format(
            'M d, Y h:i A'
        );

        $sheet->getHeaderFooter()->setOddFooter(
            '&L&8JC66 Coffee Shop POS' .
            '&C&8Page &P of &N' .
            "&R&8Generated {$generatedDate}"
        );

        /*
         * ---------------------------------------------------------
         * Hide Excel gridlines
         * ---------------------------------------------------------
         */

        $sheet->setShowGridlines(false);
    }
}