<?php

namespace App\Exports\Sheets;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;

/**
 * Shared layout for every printed inventory report sheet:
 *
 *   Row 1  JC66 COFFEE SHOP
 *   Row 2  INVENTORY MONITORING REPORT
 *   Row 3  Period: ...
 *   Row 4  Generated By: ... | Generated Date: ...
 *   Row 5  (blank)
 *   Row 6  <section heading, e.g. "1. Inventory Summary">
 *   Row 7  <column headings>
 *   Row 8+ <data rows>
 *          <optional footer/total rows>
 */
abstract class BaseReportSheet implements FromArray, ShouldAutoSize, WithEvents, WithTitle
{
    /**
     * @param  array{period:string,generated_by:string,generated_date:string}  $meta
     * @param  array<int,array<int,mixed>>  $rows  Already-formatted table rows (one array per row).
     */
    public function __construct(protected array $meta, protected array $rows)
    {
    }

    /** Excel tab name (max 31 chars, no \ / ? * [ ] characters). */
    abstract public function title(): string;

    /** The in-sheet section heading printed above the table, e.g. "1. Inventory Summary". */
    abstract public function reportHeading(): string;

    /** Column headings for the data table. */
    abstract public function headings(): array;

    /** 1-indexed column numbers that should be formatted as Philippine peso currency. */
    abstract public function currencyColumns(): array;

    /**
     * 1-indexed column number holding a status label (e.g. "Low Stock",
     * "Expired"), used for row color-coding. Null if this sheet has none.
     */
    public function statusColumn(): ?int
    {
        return null;
    }

    /**
     * Optional trailing rows (totals, etc). Each row must have the same
     * column count as headings(). Override and compute from $this->rows.
     */
    public function footerRows(): array
    {
        return [];
    }

    public function array(): array
    {
        $rows = [
            ['JC66 COFFEE SHOP'],
            ['INVENTORY MONITORING REPORT'],
            ['Period: '.($this->meta['period'] ?? '—')],
            ['Generated By: '.($this->meta['generated_by'] ?? '—').'   |   Generated Date: '.($this->meta['generated_date'] ?? '—')],
            [],
            [$this->reportHeading()],
            $this->headings(),
        ];

        if ($this->rows === []) {
            $rows[] = ['No records found for this period.'];
        } else {
            foreach ($this->rows as $row) {
                $rows[] = $row;
            }
        }

        foreach ($this->footerRows() as $footerRow) {
            $rows[] = $footerRow;
        }

        return $rows;
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $this->applyStyling($event);
            },
        ];
    }

    protected function applyStyling(AfterSheet $event): void
    {
        $sheet = $event->sheet->getDelegate();
        $colCount = max(count($this->headings()), 1);
        $lastCol = Coordinate::stringFromColumnIndex($colCount);

        // --- Banner (rows 1-4, 6) ---
        foreach ([1, 2, 3, 4, 6] as $r) {
            $sheet->mergeCells("A{$r}:{$lastCol}{$r}");
            $sheet->getStyle("A{$r}")->getAlignment()->setHorizontal('center');
        }

        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
        $sheet->getStyle('A2')->getFont()->setBold(true)->setSize(12);
        $sheet->getStyle('A3')->getFont()->setSize(10)->setItalic(true);
        $sheet->getStyle('A4')->getFont()->setSize(9)->setItalic(true);
        $sheet->getStyle('A6')->getFont()->setBold(true)->setSize(11);
        $sheet->getStyle('A6')->getAlignment()->setHorizontal('left');

        // --- Table header row (row 7) ---
        $headerRow = 7;
        $headerRange = "A{$headerRow}:{$lastCol}{$headerRow}";
        $sheet->getStyle($headerRange)->getFont()->setBold(true)->getColor()->setRGB('FFFFFF');
        $sheet->getStyle($headerRange)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('6F4E37');
        $sheet->getStyle($headerRange)->getAlignment()->setHorizontal('center')->setVertical('center');

        $dataCount = max(count($this->rows), 1);
        $lastDataRow = $headerRow + $dataCount;

        $footerCount = count($this->footerRows());
        $footerStart = $lastDataRow + 1;
        $footerEnd = $footerStart + $footerCount - 1;
        $formatEnd = $footerCount > 0 ? $footerEnd : $lastDataRow;

        // --- Table borders (header + data only) ---
        $sheet->getStyle("A{$headerRow}:{$lastCol}{$lastDataRow}")
            ->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);

        // --- Currency formatting ---
        foreach ($this->currencyColumns() as $colIndex) {
            $letter = Coordinate::stringFromColumnIndex($colIndex);
            $sheet->getStyle("{$letter}".($headerRow + 1).":{$letter}{$formatEnd}")
                ->getNumberFormat()->setFormatCode('"₱"#,##0.00');
        }

        // --- Status color-coding ---
        if ($this->rows !== [] && ($statusCol = $this->statusColumn())) {
            $letter = Coordinate::stringFromColumnIndex($statusCol);
            foreach ($this->rows as $i => $row) {
                $value = strtolower((string) ($row[$statusCol - 1] ?? ''));
                $rowNum = $headerRow + 1 + $i;
                $color = match (true) {
                    str_contains($value, 'out of stock'), str_contains($value, 'expired') => 'F8CBCB',
                    str_contains($value, 'low'), str_contains($value, 'expiring') => 'FDE8B6',
                    default => null,
                };
                if ($color) {
                    $sheet->getStyle("{$letter}{$rowNum}")
                        ->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB($color);
                }
            }
        }

        // --- Footer/total rows ---
        if ($footerCount > 0) {
            $sheet->getStyle("A{$footerStart}:{$lastCol}{$footerEnd}")->getFont()->setBold(true);
        }

        $sheet->freezePane('A'.($headerRow + 1));
        $sheet->setAutoFilter($headerRange);

        // --- Print setup ---
        $sheet->getPageSetup()
            ->setOrientation(PageSetup::ORIENTATION_LANDSCAPE)
            ->setFitToWidth(1)
            ->setFitToHeight(0);
        $sheet->getPageMargins()->setTop(0.5)->setBottom(0.5)->setLeft(0.4)->setRight(0.4);
        $sheet->getHeaderFooter()->setOddFooter(
            '&L&8Generated by JC66 Coffee Shop POS&C&8Page &P of &N&R&8'.now()->format('Y-m-d H:i')
        );
    }
}