<?php

namespace App\Exports\Sheets;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use App\Models\ShopSetting;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;

/**
 * Sheet 1 of the Sales Report export: KPIs, Payment Summary, Order Type
 * Summary, and Best Selling Products stacked on one sheet.
 *
 * Unlike the single-table inventory sheets (BaseReportSheet), this needs
 * several mini-tables, so it implements the same JC66 banner/brown-header
 * conventions directly instead of extending BaseReportSheet's
 * one-table-per-sheet shape.
 *
 * @param  array{period:string,generated_by:string,generated_date:string}  $meta
 * @param  array{
 *     summary: array,
 *     paymentSummary: array<int,array>,
 *     orderTypeSummary: array<int,array>,
 *     bestSellers: array<int,array>,
 * }  $data
 */
class SalesSummarySheet implements FromArray, ShouldAutoSize, WithEvents, WithTitle
{
    private const BROWN = '6F4E37';

    /** @var array<int,array{header:int,dataStart:int,dataEnd:int,currency:array<int,int>,percent:array<int,int>,cols:int,footer?:int}> */
    private array $blocks = [];

    /** @var array<string,string> e.g. ['B8' => 'currency', 'B14' => 'percent'] */
    private array $cellFormats = [];

    public function __construct(private array $meta, private array $data)
    {
    }

    public function title(): string
    {
        return 'Sales Summary';
    }

    public function array(): array
    {
        $rows = [
            [mb_strtoupper(ShopSetting::displayName())],
            ['SALES REPORT'],
            ['Period: '.($this->meta['period'] ?? '—')],
            ['Generated By: '.($this->meta['generated_by'] ?? '—').'   |   Generated Date: '.($this->meta['generated_date'] ?? '—')],
            [],
        ];

        $summary = $this->data['summary'] ?? [];

        // ---- 1. Sales Summary (KPIs) ----
        $rows[] = ['1. Sales Summary'];
        $headerRow = count($rows) + 1;
        $rows[] = ['Metric', 'Value'];
        $dataStart = count($rows) + 1;

        $kpis = [
            ['Total Sales', $summary['total_sales'] ?? 0, 'currency'],
            ['Total Transactions', $summary['transaction_count'] ?? 0, null],
            ['Items Sold', $summary['items_sold'] ?? 0, null],
            ['Average Sale', $summary['average_sale'] ?? 0, 'currency'],
            ['Total COGS', $summary['total_cogs'] ?? 0, 'currency'],
            ['Gross Profit', $summary['gross_profit'] ?? 0, 'currency'],
            ['Gross Margin', $summary['gross_margin'] ?? 0, 'percent'],
        ];
        foreach ($kpis as [$label, $value, $format]) {
            $rows[] = [$label, $value];
            if ($format) {
                $this->cellFormats['B'.count($rows)] = $format;
            }
        }
        $dataEnd = count($rows);
        $this->blocks[] = ['header' => $headerRow, 'dataStart' => $dataStart, 'dataEnd' => $dataEnd, 'currency' => [], 'percent' => [], 'cols' => 2];

        $rows[] = [];

        // ---- 2. Payment Summary ----
        $rows[] = ['2. Payment Summary'];
        $headerRow = count($rows) + 1;
        $rows[] = ['Payment Method', 'Transactions', 'Total Sales', 'Percentage'];
        $dataStart = count($rows) + 1;
        $paymentRows = $this->data['paymentSummary'] ?? [];
        foreach ($paymentRows as $p) {
            $rows[] = [$p['label'], $p['transactions'], $p['total_sales'], $p['percentage']];
        }
        $dataEnd = count($rows);
        $rows[] = [
            'TOTAL',
            array_sum(array_column($paymentRows, 'transactions')),
            array_sum(array_column($paymentRows, 'total_sales')),
            100,
        ];
        $footerRow = count($rows);
        $this->blocks[] = ['header' => $headerRow, 'dataStart' => $dataStart, 'dataEnd' => $footerRow, 'currency' => [3], 'percent' => [4], 'cols' => 4, 'footer' => $footerRow];

        $rows[] = [];

        // ---- 3. Order Type Summary ----
        $rows[] = ['3. Order Type Summary'];
        $headerRow = count($rows) + 1;
        $rows[] = ['Order Type', 'Transactions', 'Items Sold', 'Total Sales'];
        $dataStart = count($rows) + 1;
        $orderRows = $this->data['orderTypeSummary'] ?? [];
        foreach ($orderRows as $o) {
            $rows[] = [$o['label'], $o['transactions'], $o['items_sold'], $o['total_sales']];
        }
        $dataEnd = count($rows);
        $rows[] = [
            'TOTAL',
            array_sum(array_column($orderRows, 'transactions')),
            array_sum(array_column($orderRows, 'items_sold')),
            array_sum(array_column($orderRows, 'total_sales')),
        ];
        $footerRow = count($rows);
        $this->blocks[] = ['header' => $headerRow, 'dataStart' => $dataStart, 'dataEnd' => $footerRow, 'currency' => [4], 'percent' => [], 'cols' => 4, 'footer' => $footerRow];

        $rows[] = [];

        // ---- 4. Best Selling Products ----
        $rows[] = ['4. Best Selling Products'];
        $headerRow = count($rows) + 1;
        $rows[] = ['Product', 'Quantity Sold', 'Revenue'];
        $dataStart = count($rows) + 1;
        $bestSellers = $this->data['bestSellers'] ?? [];
        if ($bestSellers === []) {
            $rows[] = ['No sales in this period.', '', ''];
        } else {
            foreach ($bestSellers as $b) {
                $rows[] = [$b['name'], $b['quantity'], $b['total']];
            }
        }
        $dataEnd = count($rows);
        $this->blocks[] = ['header' => $headerRow, 'dataStart' => $dataStart, 'dataEnd' => $dataEnd, 'currency' => [3], 'percent' => [], 'cols' => 3];

        return $rows;
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $this->applyStyling($event);
            },
        ];
    }

    private function applyStyling(AfterSheet $event): void
    {
        $sheet = $event->sheet->getDelegate();

        foreach ([1, 2, 3, 4] as $r) {
            $sheet->mergeCells("A{$r}:D{$r}");
            $sheet->getStyle("A{$r}")->getAlignment()->setHorizontal('center');
        }
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
        $sheet->getStyle('A2')->getFont()->setBold(true)->setSize(12);
        $sheet->getStyle('A3')->getFont()->setSize(10)->setItalic(true);
        $sheet->getStyle('A4')->getFont()->setSize(9)->setItalic(true);

        foreach ($this->blocks as $block) {
            $lastCol = Coordinate::stringFromColumnIndex($block['cols']);
            $headingRow = $block['header'] - 1;
            $sheet->getStyle("A{$headingRow}")->getFont()->setBold(true)->setSize(11);

            $headerRange = "A{$block['header']}:{$lastCol}{$block['header']}";
            $sheet->getStyle($headerRange)->getFont()->setBold(true)->getColor()->setRGB('FFFFFF');
            $sheet->getStyle($headerRange)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::BROWN);
            $sheet->getStyle($headerRange)->getAlignment()->setHorizontal('center');

            $sheet->getStyle("A{$block['header']}:{$lastCol}{$block['dataEnd']}")
                ->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);

            foreach ($block['currency'] as $col) {
                $letter = Coordinate::stringFromColumnIndex($col);
                $sheet->getStyle("{$letter}{$block['dataStart']}:{$letter}{$block['dataEnd']}")
                    ->getNumberFormat()->setFormatCode('"₱"#,##0.00');
            }
            foreach ($block['percent'] as $col) {
                $letter = Coordinate::stringFromColumnIndex($col);
                $sheet->getStyle("{$letter}{$block['dataStart']}:{$letter}{$block['dataEnd']}")
                    ->getNumberFormat()->setFormatCode('0.00"%"');
            }

            if (isset($block['footer'])) {
                $sheet->getStyle("A{$block['footer']}:{$lastCol}{$block['footer']}")->getFont()->setBold(true);
            }
        }

        // KPI block cells are mixed types (currency/plain-number/percent),
        // so each is formatted individually rather than as a column range.
        foreach ($this->cellFormats as $cell => $type) {
            $format = $type === 'currency' ? '"₱"#,##0.00' : '0.00"%"';
            $sheet->getStyle($cell)->getNumberFormat()->setFormatCode($format);
        }

        $sheet->getPageSetup()
            ->setOrientation(PageSetup::ORIENTATION_PORTRAIT)
            ->setFitToWidth(1)
            ->setFitToHeight(0);
        $sheet->getPageMargins()->setTop(0.5)->setBottom(0.5)->setLeft(0.4)->setRight(0.4);
        $sheet->getHeaderFooter()->setOddFooter(
            '&L&8Generated by ' . ShopSetting::displayName() . ' POS&C&8Page &P of &N&R&8'.now()->format('Y-m-d H:i')
        );
    }
}
